services:
  yookassa-to-mynalog:
    container_name: yookassa-to-mynalog
    hostname: yookassa-to-mynalog
    image: grandvan/yookassa-to-mynalog:latest
    restart: always
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    dns:
      - 77.88.8.8
      - 77.88.8.1
    environment:
      - PYTHONUNBUFFERED=1